# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='dta_nasc',
            field=models.DateField(null=True),
        ),
    ]
