# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 23:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0003_auto_20160302_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dta_nasc',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
