# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-03 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0004_auto_20160302_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cpf',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
