# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 14:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0006_auto_20160303_1018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condominium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rsocial', models.CharField(max_length=80)),
                ('cnpj', models.CharField(max_length=20, unique=True)),
                ('tel', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=80)),
                ('number', models.CharField(blank=True, max_length=5)),
                ('compl', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Condominio',
                'verbose_name_plural': 'Condominios',
            },
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Dados Pessoais'},
        ),
        migrations.AlterField(
            model_name='customer',
            name='compl',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='condominium',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='condominium.Customer'),
        ),
    ]
