# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 00:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominium', '0010_auto_20160310_1921'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'verbose_name': 'Plano'},
        ),
        migrations.AddField(
            model_name='plan',
            name='condominium_count',
            field=models.IntegerField(default=1),
        ),
    ]
